### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by InTheCloudDan** [jsok/puppet-vault#139]
With 1.2.8 being released in 2017 and there being 60 commits to master since that time I just wanted to check to see if there was any timeline on a new release being created?

**Comment by jsok** [comment]
Those commits since 1.2.8 are breaking changes therefore need to be minted under a 2.0 release.

The timeline and progress for 2.0 is listed  https://github.com/jsok/puppet-vault#path-to-20  and https://github.com/jsok/puppet-vault/milestone/1 .

There's still some pertinent things IMHO to address like dropping Puppet 3 support and fixing systemd compatibility.

I haven't actually professionally coded Puppet for > 3 years now so maintaining this is hard since I'm not up to date on the new Puppet advancements.
Similarly a lot of PRs I get simply ignore the PR template and are essentially drive-by patches and when asked to add tests I never receive a response.

Hopefully this give everyone some insight into the state of this module. Thanks for your patience.

**Comment by InTheCloudDan** [comment]
Understood, I should have lead off with thanks I really do appreciate the work you did on this!! It's was straightforward to get vault installed. I didn't realize master branch had the breaking changes in it.

**Comment by jsok** [comment]
Closed by https://github.com/jsok/puppet-vault/commit/38344ab7902631a04c7c2de44411eb3585c99892
