### ISSUE TITLE
Upgrade path?

### ISSUE THREAD

**Issue by hobbeswalsh** [jsok/puppet-vault#4]
Hi there,

I'm trying to experiment with upgrading Vault in a VM environment before I do it live -- what's the right way to upgrade Vault using this module? It looks to me as though the `$download_url` parameter is hard-coded, so without merging a PR into these manifests (and pushing to forge, and re-downloading, etc...) what would you recommend as a way to start using this module to manage a different version of Vault?

Thanks!

**Comment by jsok** [comment]
The `download_url` in `params.pp` is just the default URL. You can override the URL by setting it directly on the `vault` class:

```puppet
class '::vault' {
   download_url => 'https://your-url',
}
```

Or via hiera:

```yml
vault::download_url: https://your-url
```

However I suspect that if you change the download url and re-run puppet on an existing vault 0.2.0 install, it won't upgrade and restart the service. I may be wrong, but I'd be interested in knowing what happens if/when you try it.

**Comment by 0x9090** [comment]
I deployed a development version of Vault by changing the download_url, and the module seems to have picked up that this is a new file, and placed it correctly. But I only tried this once, so more testing should be done to ensure that this works as expected
