### ISSUE TITLE
Support sighup for reloads on systemd/service

### ISSUE THREAD

**Issue by leeuwenrjj** [jsok/puppet-vault#86]
You might want to reload vault (e.g. certificate change) without a full restart.
(which needs a vault unseal again)
This seems to be supported on the vault side with a SIGHUP.
Needs implementation in module

**Comment by jsok** [comment]
The tricky part is differentiating which config parameters have changed and which constitute a restart vs reload.

AFAICT only the `tcp` listener `tls_cert_file` and `tls_key_file` are the only options which will take effect after a reload (https://www.vaultproject.io/docs/configuration/listener/tcp.html).
So we could selectively look for these in the config hash and e.g. notify a separate `vault_reload` class rather than the `Service[vault]` proper.

**Comment by leeuwenrjj** [comment]
I would prefer it would just look if the cert files on the filesystem changed and reload if that happens. E.g. we have let's encrypt keys managed with puppet outside of this class. 
This would update those certs while not changeing the config hash for the certs.
Now I do something not so pretty, something like this:
  exec { 'sighub_vault':
    command => '/bin/pkill -sig 1 vault',
  }
Letsencrypt['vault']   ~> Exec['sighub_vault']

**Comment by jsok** [comment]
The vault module isn't responsible for managing the `File[]` resource, how it gets on the system isn't its concern.
So if the vault module doesn't manage the resource, it shouldn't be responsible for wiring up the reload/refresh.

What you're doing now is the right approach, i.e. you should be wiring up the relationship between the `Letsencrypt[vault]` and `Service[vault]` resources.

**Comment by jsok** [comment]
@leeuwenrjj if you have any more comments or have some more reasons why you think this should be a responsibility of this module feel free to comment and re-open.
